-- =====================================================
-- BRONZE LAYER: RAW DATA INGESTION (As-Is)
-- =====================================================
-- These tables receive raw data with minimal transformation
-- Change tracking enabled for CDC

USE DATABASE SMOOTHIES;
CREATE SCHEMA IF NOT EXISTS BRONZE;
USE SCHEMA BRONZE;

-- 1. Raw Orders Table
CREATE OR REPLACE TABLE BRONZE.ORDERS_RAW (
    ORDER_ID STRING DEFAULT UUID_STRING() PRIMARY KEY,
    NAME_ON_ORDER STRING NOT NULL,
    INGREDIENTS STRING NOT NULL,
    ORDER_FILLED BOOLEAN DEFAULT FALSE,
    ORDER_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    SOURCE_SYSTEM STRING DEFAULT 'streamlit_app',
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
)
CHANGE_TRACKING = ON;

-- 2. Raw Fruit Options Table
CREATE OR REPLACE TABLE BRONZE.FRUIT_OPTIONS_RAW (
    FRUIT_ID STRING DEFAULT UUID_STRING() PRIMARY KEY,
    FRUIT_NAME STRING NOT NULL UNIQUE,
    SEARCH_ON STRING NOT NULL,
    CATEGORY STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
)
CHANGE_TRACKING = ON;

-- 3. Raw Nutrition Data (from API)
CREATE OR REPLACE TABLE BRONZE.NUTRITION_DATA_RAW (
    NUTRITION_ID STRING DEFAULT UUID_STRING() PRIMARY KEY,
    FRUIT_NAME STRING NOT NULL,
    CALORIES FLOAT,
    FAT FLOAT,
    PROTEIN FLOAT,
    CARBOHYDRATES FLOAT,
    SUGAR FLOAT,
    FIBER FLOAT,
    POTASSIUM FLOAT,
    VITAMIN_C FLOAT,
    RAW_JSON VARIANT,
    API_CALL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
)
CHANGE_TRACKING = ON;

-- 4. Raw Inventory Table
CREATE OR REPLACE TABLE BRONZE.INVENTORY_RAW (
    INVENTORY_ID STRING DEFAULT UUID_STRING() PRIMARY KEY,
    FRUIT_ID STRING,
    FRUIT_NAME STRING NOT NULL,
    QUANTITY_IN_STOCK FLOAT,
    UNIT_OF_MEASURE STRING DEFAULT 'KG',
    REORDER_LEVEL FLOAT,
    SUPPLIER_ID STRING,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
)
CHANGE_TRACKING = ON;

-- Insert sample data into Bronze
INSERT INTO BRONZE.FRUIT_OPTIONS_RAW (FRUIT_NAME, SEARCH_ON, CATEGORY)
VALUES
    ('Apples', 'apple', 'Citrus'),
    ('Blueberries', 'blueberry', 'Berries'),
    ('Strawberries', 'strawberry', 'Berries'),
    ('Banana', 'banana', 'Tropical'),
    ('Mango', 'mango', 'Tropical'),
    ('Kiwi', 'kiwi', 'Citrus'),
    ('Watermelon', 'watermelon', 'Melons'),
    ('Orange', 'orange', 'Citrus');

INSERT INTO BRONZE.INVENTORY_RAW (FRUIT_ID, FRUIT_NAME, QUANTITY_IN_STOCK, REORDER_LEVEL)
VALUES
    ('FRUIT_001', 'Apples', 150.0, 50.0),
    ('FRUIT_002', 'Blueberries', 80.0, 30.0),
    ('FRUIT_003', 'Strawberries', 100.0, 40.0),
    ('FRUIT_004', 'Banana', 200.0, 75.0),
    ('FRUIT_005', 'Mango', 120.0, 45.0),
    ('FRUIT_006', 'Kiwi', 90.0, 35.0),
    ('FRUIT_007', 'Watermelon', 60.0, 20.0),
    ('FRUIT_008', 'Orange', 140.0, 50.0);
