-- =====================================================
-- SILVER LAYER: CLEANED & DEDUPLICATED DATA
-- =====================================================
-- Cleaned, deduplicated, and validated data
-- Ready for analytics use

CREATE SCHEMA IF NOT EXISTS SILVER;
USE SCHEMA SILVER;

-- 1. Cleaned Orders
CREATE OR REPLACE TABLE SILVER.ORDERS (
    ORDER_ID STRING NOT NULL PRIMARY KEY,
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING NOT NULL,
    ORDER_DATE DATE,
    ORDER_MONTH STRING,
    ORDER_YEAR INT,
    INGREDIENTS STRING NOT NULL,
    NUM_INGREDIENTS INT,
    ORDER_STATUS STRING DEFAULT 'Pending',
    ORDER_CREATED_AT TIMESTAMP_NTZ,
    ORDER_UPDATED_AT TIMESTAMP_NTZ,
    DATA_QUALITY_FLAG BOOLEAN DEFAULT TRUE,
    SILVER_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Cleaned Customers (Dimension)
CREATE OR REPLACE TABLE SILVER.CUSTOMERS (
    CUSTOMER_ID STRING NOT NULL PRIMARY KEY,
    CUSTOMER_NAME STRING UNIQUE,
    FIRST_ORDER_DATE DATE,
    LAST_ORDER_DATE DATE,
    TOTAL_ORDERS INT DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ,
    SILVER_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. Cleaned Fruits (Dimension)
CREATE OR REPLACE TABLE SILVER.FRUITS (
    FRUIT_ID STRING NOT NULL PRIMARY KEY,
    FRUIT_NAME STRING UNIQUE,
    SEARCH_ON STRING,
    CATEGORY STRING,
    VENDOR STRING DEFAULT 'Local Supplier',
    UNIT_COST FLOAT DEFAULT 2.5,
    SILVER_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. Cleaned Nutrition Data
CREATE OR REPLACE TABLE SILVER.NUTRITION_DATA (
    NUTRITION_ID STRING NOT NULL PRIMARY KEY,
    FRUIT_ID STRING,
    FRUIT_NAME STRING,
    CALORIES FLOAT DEFAULT 0,
    FAT FLOAT DEFAULT 0,
    PROTEIN FLOAT DEFAULT 0,
    CARBOHYDRATES FLOAT DEFAULT 0,
    SUGAR FLOAT DEFAULT 0,
    FIBER FLOAT DEFAULT 0,
    POTASSIUM FLOAT DEFAULT 0,
    SERVING_SIZE_GRAMS FLOAT DEFAULT 100,
    API_LAST_UPDATED TIMESTAMP_NTZ,
    SILVER_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. Cleaned Inventory
CREATE OR REPLACE TABLE SILVER.INVENTORY (
    INVENTORY_ID STRING NOT NULL PRIMARY KEY,
    FRUIT_ID STRING,
    FRUIT_NAME STRING NOT NULL,
    CURRENT_STOCK FLOAT DEFAULT 0,
    UNIT_OF_MEASURE STRING DEFAULT 'KG',
    REORDER_LEVEL FLOAT,
    REORDER_QUANTITY FLOAT DEFAULT 50.0,
    LAST_STOCK_UPDATE TIMESTAMP_NTZ,
    IS_LOW_STOCK BOOLEAN DEFAULT FALSE,
    SILVER_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX idx_orders_customer ON SILVER.ORDERS(CUSTOMER_ID);
CREATE INDEX idx_orders_date ON SILVER.ORDERS(ORDER_DATE);
CREATE INDEX idx_customers_active ON SILVER.CUSTOMERS(IS_ACTIVE);
